name: example
description: "A project to showcase http and Alice integration."
publish_to: 'none'
version: 1.0.0+3
resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
  alice_http:
  http: ^1.4.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
