name: alice_dio_example
description: "A project to showcase dio and alice integration."
publish_to: 'none'
version: 1.0.0+3
resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice:
  alice_dio:
  path_provider:
  path:
  dio: ^5.8.0+1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
