name: alice_example
description: "Example project to showcase Alice."
publish_to: 'none'
version: 1.0.0+3
resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  alice:

dev_dependencies:
  build_runner:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
